name: Sync Sheets to CSV

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decrypt credentials
        run: |
          echo "$GOOGLE_CREDS" > google_credentials.json
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run sync script
        run: python sync_sheets_to_csv.py

      - name: Commit and push
        run: |
          git config --global user.email "sync-bot@example.com"
          git config --global user.name "sync-bot"
          git add exports/*.csv.gz
          git commit -m "🔄 Sync on $(date -u +"%Y-%m-%d %H:%M")" || echo "No changes"
          git push
